# Generated by Django 5.1.4 on 2025-01-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_rename_price_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='c_image',
            field=models.ImageField(default='/', upload_to='Items/'),
        ),
    ]
