# Generated by Django 5.1.4 on 2025-01-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Price',
            new_name='price',
        ),
    ]
